runtime: python27
api_version: 1
threadsafe: yes
service: minesweeper

handlers:
- url: .*
  script: minesweeper.app
  
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 100ms
  max_pending_latency: automatic
  max_concurrent_requests: 100